import { resolve } from 'node:path';
import { defineConfig } from 'wxt';
import { nodePolyfills } from 'vite-plugin-node-polyfills';
import pkg from './package.json';

const srcDir = resolve(__dirname, 'src');

// Wraps the injected inpage script in an IIFE so it doesn't leak into the
// page's global scope. Ported from the old vite.production.config.ts plugin.
let hasProcessedInPage = false;
const makeInpageScriptIife = {
    name: 'make-inpage-script-in-iife',
    generateBundle(_outputOptions: unknown, bundle: Record<string, { code?: string }>) {
        for (const [fileName, file] of Object.entries(bundle)) {
            if (!hasProcessedInPage && fileName.includes('inpage') && file.code != null) {
                file.code = `(() => {\n${file.code}})()`;
                hasProcessedInPage = true;
            }
        }
    },
};

// https://wxt.dev/api/config.html
export default defineConfig({
    modules: ['@wxt-dev/module-react'],
    srcDir: 'src',
    outDir: 'dist',
    // public/ lives at the repo root, not under srcDir.
    publicDir: resolve(__dirname, 'public'),
    alias: {
        '@/app': srcDir,
        '@': srcDir,
    },
    // Ported from src/manifest.chrome.json (MV3) and src/manifest.firefox.json
    // (MV2). action/background/content_scripts are generated by wxt from the
    // entrypoints; only the non-generated bits live here, branched per MV.
    manifest: ({ manifestVersion }) => ({
        name: 'ARK Connect',
        description:
            'ARK Connect is an open source browser extension that allows users to connect their ARK address to Web3 applications.',
        version: pkg.version,
        icons: {
            16: 'icon/16.png',
            32: 'icon/32.png',
            48: 'icon/48.png',
            128: 'icon/128.png',
        },
        permissions: [
            'activeTab',
            'storage',
            'clipboardWrite',
            'tabs',
            'unlimitedStorage',
            'commands',
        ],
        web_accessible_resources:
            manifestVersion === 3
                ? [{ resources: ['inpage.js'], matches: ['<all_urls>'] }]
                : ['inpage.js'],
        commands: {
            [manifestVersion === 3 ? '_execute_action' : '_execute_browser_action']: {
                suggested_key: { default: 'Shift+Alt+C' },
                description: 'Open the extension',
            },
        },
    }),
    vite: () => ({
        define: {
            'process.env.NODE_DEBUG': process.env.NODE_DEBUG ? true : false,
            'process.env.VITE_SEED_ADDRESSES': process.env.VITE_SEED_ADDRESSES ? true : false,
        },
        plugins: [
            nodePolyfills({
                // protocol import handling confuses WXT's vite-node loader
                protocolImports: false,
                include: [
                    'buffer',
                    'os',
                    'process',
                    'path',
                    'http',
                    'https',
                    'module',
                    'util',
                    'events',
                    'string_decoder',
                    'url',
                ],
                globals: {
                    Buffer: true,
                    global: true,
                    // Must be polyfilled in production too: the MV3 service
                    // worker has no `process`, and deps like localForage
                    // reference it at runtime in background.js. Gating this on
                    // dev (serve) broke `pnpm build` with "process is not
                    // defined" while `pnpm dev` worked.
                    process: true,
                },
            }),
            makeInpageScriptIife,
        ],
        optimizeDeps: {
            esbuildOptions: {
                target: 'es2020',
            },
        },
        build: {
            target: 'es2020',
        },
    }),
});
