import { resolve } from 'node:path';
import { defineConfig } from 'wxt';
import { loadEnv } from 'vite';
import { nodePolyfills } from 'vite-plugin-node-polyfills';
import pkg from './package.json';

const srcDir = resolve(__dirname, 'src');

// wxt evaluates this config under vite-node before vite's env loading kicks
// in, so .env values aren't visible via process.env. Load them ourselves so
// VITE_START_URL / VITE_FIREFOX_BINARY (consumed below in webExt) resolve from
// .env. Shell env still wins because it's spread last.
process.env = { ...loadEnv('', process.cwd(), ''), ...process.env };

// wxt builds the unlisted inpage script as a named IIFE (`var inpage = ...`)
// followed by a trailing `inpage;` footer that is appended after the chunk is
// generated. Wrapping the final code in an IIFE keeps top-level `var inpage`
// off the page's window. Runs `post` so it also encloses that footer —
// otherwise the footer sits outside the wrapper and `inpage` is undefined.
const makeInpageScriptIife = {
    name: 'make-inpage-script-in-iife',
    enforce: 'post' as const,
    generateBundle(_outputOptions: unknown, bundle: Record<string, { code?: string }>) {
        for (const [fileName, file] of Object.entries(bundle)) {
            if (fileName.includes('inpage') && file.code != null && !file.code.startsWith('(()')) {
                file.code = `(() => {\n${file.code}\n})()`;
            }
        }
    },
};

// https://wxt.dev/api/config.html
export default defineConfig({
    modules: ['@wxt-dev/module-react'],
    srcDir: 'src',
    outDir: 'dist',
    // public/ lives at the repo root, not under srcDir.
    publicDir: resolve(__dirname, 'public'),
    alias: {
        '@/app': srcDir,
        '@': srcDir,
    },
    webExt: {
        startUrls: process.env.VITE_START_URL ? [process.env.VITE_START_URL] : undefined,
        binaries: process.env.VITE_FIREFOX_BINARY
            ? { firefox: process.env.VITE_FIREFOX_BINARY }
            : undefined,
    },
    // action/background/content_scripts are generated by wxt from the
    // entrypoints; only the non-generated bits live here, branched per MV.
    manifest: ({ manifestVersion }) => ({
        name: 'ARK Connect',
        description:
            'ARK Connect is an open source browser extension that allows users to connect their ARK address to Web3 applications.',
        version: pkg.version,
        icons: {
            16: 'icon/16.png',
            32: 'icon/32.png',
            48: 'icon/48.png',
            128: 'icon/128.png',
        },
        permissions: [
            'activeTab',
            'storage',
            'clipboardWrite',
            'tabs',
            'unlimitedStorage',
            'sidePanel',
        ],
        web_accessible_resources:
            manifestVersion === 3
                ? [{ resources: ['inpage.js'], matches: ['<all_urls>'] }]
                : ['inpage.js'],
        commands: {
            [manifestVersion === 3 ? '_execute_action' : '_execute_browser_action']: {
                suggested_key: { default: 'Shift+Alt+C' },
                description: 'Open the extension',
            },
        },
    }),
    vite: () => ({
        define: {
            'process.env.NODE_DEBUG': process.env.NODE_DEBUG ? true : false,
            'process.env.VITE_SEED_ADDRESSES': process.env.VITE_SEED_ADDRESSES ? true : false,
        },
        plugins: [
            nodePolyfills({
                // protocol import handling confuses WXT's vite-node loader
                protocolImports: false,
                include: [
                    'buffer',
                    'os',
                    'process',
                    'path',
                    'http',
                    'https',
                    'module',
                    'util',
                    'events',
                    'string_decoder',
                    'url',
                ],
                globals: {
                    Buffer: true,
                    global: true,
                    // The MV3 service worker has no `process`, and deps like
                    // localForage reference it at runtime in background.js, so
                    // it must be polyfilled in production builds too.
                    process: true,
                },
            }),
            makeInpageScriptIife,
        ],
        optimizeDeps: {
            esbuildOptions: {
                target: 'es2020',
            },
        },
        build: {
            target: 'es2020',
        },
    }),
});
