// Generated by wxt
export {}
declare global {
  const ContentScriptContext: typeof import('wxt/utils/content-script-context').ContentScriptContext
  const InvalidMatchPattern: typeof import('wxt/utils/match-patterns').InvalidMatchPattern
  const LogoIcon: typeof import('/Users/alfonsobries/Projects/Ark/arkconnect-extension/src/components/Logo').LogoIcon
  const MatchPattern: typeof import('wxt/utils/match-patterns').MatchPattern
  const NextPageMiddleware: typeof import('/Users/alfonsobries/Projects/Ark/arkconnect-extension/src/components/NextPageMiddleware').default
  const assertArray: typeof import('/Users/alfonsobries/Projects/Ark/arkconnect-extension/src/utils/assertions').assertArray
  const assertConfirmedTransaction: typeof import('/Users/alfonsobries/Projects/Ark/arkconnect-extension/src/utils/assertions').assertConfirmedTransaction
  const assertNetwork: typeof import('/Users/alfonsobries/Projects/Ark/arkconnect-extension/src/utils/assertions').assertNetwork
  const assertNumber: typeof import('/Users/alfonsobries/Projects/Ark/arkconnect-extension/src/utils/assertions').assertNumber
  const assertProfile: typeof import('/Users/alfonsobries/Projects/Ark/arkconnect-extension/src/utils/assertions').assertProfile
  const assertReadOnlyWallet: typeof import('/Users/alfonsobries/Projects/Ark/arkconnect-extension/src/utils/assertions').assertReadOnlyWallet
  const assertSignedTransaction: typeof import('/Users/alfonsobries/Projects/Ark/arkconnect-extension/src/utils/assertions').assertSignedTransaction
  const assertString: typeof import('/Users/alfonsobries/Projects/Ark/arkconnect-extension/src/utils/assertions').assertString
  const assertToken: typeof import('/Users/alfonsobries/Projects/Ark/arkconnect-extension/src/utils/assertions').assertToken
  const assertWallet: typeof import('/Users/alfonsobries/Projects/Ark/arkconnect-extension/src/utils/assertions').assertWallet
  const browser: typeof import('/Users/alfonsobries/Projects/Ark/arkconnect-extension/src/utils/platform').browser
  const createIframeUi: typeof import('wxt/utils/content-script-ui/iframe').createIframeUi
  const createIntegratedUi: typeof import('wxt/utils/content-script-ui/integrated').createIntegratedUi
  const createShadowRootUi: typeof import('wxt/utils/content-script-ui/shadow-root').createShadowRootUi
  const defineAppConfig: typeof import('wxt/utils/define-app-config').defineAppConfig
  const defineBackground: typeof import('wxt/utils/define-background').defineBackground
  const defineContentScript: typeof import('wxt/utils/define-content-script').defineContentScript
  const defineUnlistedScript: typeof import('wxt/utils/define-unlisted-script').defineUnlistedScript
  const defineWxtPlugin: typeof import('wxt/utils/define-wxt-plugin').defineWxtPlugin
  const delay: typeof import('/Users/alfonsobries/Projects/Ark/arkconnect-extension/src/utils/delay').delay
  const fakeBrowser: typeof import('wxt/testing').fakeBrowser
  const getAppConfig: typeof import('wxt/utils/app-config').getAppConfig
  const injectScript: typeof import('wxt/utils/inject-script').injectScript
  const isE2E: typeof import('/Users/alfonsobries/Projects/Ark/arkconnect-extension/src/utils/test-helpers').isE2E
  const isPreview: typeof import('/Users/alfonsobries/Projects/Ark/arkconnect-extension/src/utils/test-helpers').isPreview
  const isUnit: typeof import('/Users/alfonsobries/Projects/Ark/arkconnect-extension/src/utils/test-helpers').isUnit
  const shouldUseDarkColors: typeof import('/Users/alfonsobries/Projects/Ark/arkconnect-extension/src/utils/theme').shouldUseDarkColors
  const shouldUseDimColors: typeof import('/Users/alfonsobries/Projects/Ark/arkconnect-extension/src/utils/theme').shouldUseDimColors
  const storage: typeof import('wxt/utils/storage').storage
  const useAppConfig: typeof import('wxt/utils/app-config').useAppConfig
  const useCallback: typeof import('react').useCallback
  const useContext: typeof import('react').useContext
  const useEffect: typeof import('react').useEffect
  const useMemo: typeof import('react').useMemo
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useState: typeof import('react').useState
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Browser } from 'wxt/browser'
  import('wxt/browser')
  // @ts-ignore
  export type { WxtStorage, WxtStorageItem, StorageArea, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage'
  import('wxt/utils/storage')
  // @ts-ignore
  export type { WxtWindowEventMap } from 'wxt/utils/content-script-context'
  import('wxt/utils/content-script-context')
  // @ts-ignore
  export type { IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe'
  import('wxt/utils/content-script-ui/iframe')
  // @ts-ignore
  export type { IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated'
  import('wxt/utils/content-script-ui/integrated')
  // @ts-ignore
  export type { ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root'
  import('wxt/utils/content-script-ui/shadow-root')
  // @ts-ignore
  export type { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types'
  import('wxt/utils/content-script-ui/types')
  // @ts-ignore
  export type { WxtAppConfig } from 'wxt/utils/define-app-config'
  import('wxt/utils/define-app-config')
  // @ts-ignore
  export type { ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script'
  import('wxt/utils/inject-script')
}
