export enum ProfilePaths {
    Welcome = '/',
    Dashboard = '/profiles/:profileId/dashboard',
    Exchange = '/profiles/:profileId/exchange',
    Contacts = '/profiles/:profileId/contacts',
    SignMessage = '/profiles/:profileId/dashboard?method=sign',
    VerifyMessage = '/profiles/:profileId/verify-message',
    VerifyMessageWallet = '/profiles/:profileId/wallets/:walletId/verify-message',
    SendTransfer = '/profiles/:profileId/dashboard?method=transfer',
    SendVote = '/profiles/:profileId/votes?method=vote',
    CreateProfile = '/profiles/create',
    ImportProfile = '/profiles/import',
    Settings = '/profiles/:profileId/settings',
    PasswordSettings = '/profiles/:profileId/settings/password',
    ExportSettings = '/profiles/:profileId/settings/export',
    GeneralSettings = '/profiles/:profileId/settings/general',
    ServerManagmentSettings = '/profiles/:profileId/settings/servers',
    Votes = '/profiles/:profileId/votes',
    VotesWallet = '/profiles/:profileId/wallets/:walletId/votes',
    Tokens = '/profiles/:profileId/tokens',
}
