name: Dependencies

on:
    schedule:
        - cron: '0 0 * * 0'
    workflow_dispatch:

jobs:
    js:
        concurrency:
            group: ${{ github.head_ref }}-js
            cancel-in-progress: true

        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}

            - uses: pnpm/action-setup@v4
              with:
                  version: 8

            - uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Update JS dependencies
              run: npx npm-check-updates --configFilePath ./

            - name: Install Updated JS dependencies
              run: pnpm i --frozen-lockfile=false

            - name: Rebuild assets
              run: pnpm build

            - name: Create Pull Request
              id: cpr
              uses: peter-evans/create-pull-request@v4
              with:
                  token: ${{ secrets.GH_TOKEN }}
                  commit-message: 'chore: update JavaScript dependencies'
                  committer: GitHub <noreply@github.com>
                  author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
                  branch: chore/update-javascript-dependencies
                  delete-branch: true
                  title: 'chore: update JavaScript dependencies'
                  draft: false
